# Generated by Django 6.0.3 on 2026-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('music', models.FileField(default='music/default.mp3', upload_to='music/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
